#
# Docker setups to test and develop this application.
#
# Build and run all tests via docker-compose up test
version: '3.0'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret


  test:
    build: .
    volumes:
    - .:/code:z
    working_dir: /code
    links:
      - mongo
    entrypoint: /bin/sh
    command: -c 'pip install tox && tox'


  simple:
    build: .
    volumes:
    - .:/code
    ports:
    - "5000:5000"
    - "8443:8443"
